/*
  # Create Business Units Table

  1. New Tables
    - `tcBu`
      - Basic business unit information
      - Contact details and location
      - Tax information (RFC)

  2. Schema Updates
    - Primary key constraint on id
    - Timestamp tracking
    - Optional fields for address and tax info
*/

CREATE TABLE IF NOT EXISTS "tcBu" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  "Descripcion" text NOT NULL,
  "Calle" text NULL,
  "Colonia" text NULL,
  "Ciudad" text NULL,
  "Estado" text NULL,
  "CP" smallint NULL,
  "RFC" text NULL,
  "IdVigencia" smallint NULL,
  CONSTRAINT tcBu_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;